import { useState } from 'react';
import InputField from '../components/InputField';
import SolveButton from '../components/SolveButton';
import StepDisplay from '../components/StepDisplay';
import TabButton, { ExampleButton } from '../components/TabButton';
import BarChartViz, { FrequencyTable } from '../components/BarChartViz';
import GroupedHistogram from '../components/GroupedHistogram';
import { solveStatistics, solveGroupedStatistics, solveProportionality, solvePercentage, type Step, type StatsResult, type GroupedStatsResult } from '../utils/mathEngine';
import { parseNumberInput, parseOptionalNumber, parseNumberList, errorSteps } from '../utils/input';

export default function StatsTopic() {
  const [tab, setTab] = useState<'stats'|'grouped'|'proportion'|'percent'>('stats');
  const [values, setValues] = useState(''); const [freqs, setFreqs] = useState('');
  const [stSteps, setStSteps] = useState<Step[]>([]); const [stResult, setStResult] = useState('');
  const [statsData, setStatsData] = useState<StatsResult | null>(null);
  const [bounds,setBounds]=useState('0, 5, 10, 15, 20'); const [groupFreqs,setGroupFreqs]=useState('17, 11, 12, 10');
  const [grouped,setGrouped]=useState<GroupedStatsResult|null>(null); const [groupSteps,setGroupSteps]=useState<Step[]>([]); const [groupResult,setGroupResult]=useState('');
  const [px1, setPx1] = useState(''); const [py1, setPy1] = useState(''); const [px2, setPx2] = useState(''); const [py2, setPy2] = useState('');
  const [prSteps, setPrSteps] = useState<Step[]>([]); const [prResult, setPrResult] = useState('');
  const [pType, setPType] = useState('of'); const [pVal, setPVal] = useState(''); const [pPer, setPPer] = useState('');
  const [peSteps, setPeSteps] = useState<Step[]>([]); const [peResult, setPeResult] = useState('');

  const solveSt = () => { try { const vals=parseNumberList(values,'Valeurs'); const fqs=freqs.trim()?parseNumberList(freqs,'Effectifs'):undefined; const r=solveStatistics(vals,fqs); setStSteps(r.steps);setStResult(r.result);setStatsData(r);}catch(e){setStSteps(errorSteps(e));setStResult('');setStatsData(null);} };
  const solveGrouped=()=>{try{const r=solveGroupedStatistics(parseNumberList(bounds,'Bornes'),parseNumberList(groupFreqs,'Effectifs'));setGrouped(r);setGroupSteps(r.steps);setGroupResult(r.result);}catch(e){setGrouped(null);setGroupSteps(errorSteps(e));setGroupResult('');}};
  const solvePr = () => { try { const r = solveProportionality(parseNumberInput(px1,'x₁'), parseNumberInput(py1,'y₁'), parseNumberInput(px2,'x₂'), parseOptionalNumber(py2,'y₂')); setPrSteps(r.steps); setPrResult(r.result); } catch (e) { setPrSteps(errorSteps(e)); setPrResult(''); } };
  const solvePe = () => { try { const r = solvePercentage(pType, parseNumberInput(pVal,pType==='whatPercent'?'Total':'Valeur'), parseNumberInput(pPer,pType==='whatPercent'?'Partie':'Pourcentage')); setPeSteps(r.steps); setPeResult(r.result); } catch (e) { setPeSteps(errorSteps(e)); setPeResult(''); } };

  return <div className="space-y-6">
    <div className="flex gap-2 flex-wrap">{([['stats','Série simple'],['grouped','Classes & histogramme'],['proportion','Proportionnalité'],['percent','Pourcentages']] as const).map(([id,label])=><TabButton key={id} active={tab===id} onClick={()=>setTab(id)}>{label}</TabButton>)}</div>

    {tab==='stats'&&<><p className="text-sm text-[--color-text-secondary]">Série non regroupée : moyenne, médiane, quartiles, mode, fréquences et diagramme.</p><div className="flex flex-wrap gap-2"><ExampleButton onClick={()=>{setValues('12, 14, 14, 16, 16, 16, 18, 20');setFreqs('');}}>Notes</ExampleButton><ExampleButton onClick={()=>{setValues('5, 10, 15, 20');setFreqs('2, 5, 8, 3');}}>Avec effectifs</ExampleButton></div><InputField label="Valeurs" value={values} onChange={setValues} placeholder="10, 15, 20, 25, 30"/><InputField label="Effectifs (optionnel)" value={freqs} onChange={setFreqs} placeholder="3, 5, 8, 4, 2"/><SolveButton onClick={solveSt} label="Calculer"/>{statsData&&<><div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{[{label:'Moyenne',value:statsData.mean.toFixed(2)},{label:'Médiane',value:`${statsData.median}`},{label:'Q1',value:`${statsData.q1}`},{label:'Q3',value:`${statsData.q3}`}].map(c=><div key={c.label} className="p-3 rounded-xl bg-[--color-inset] text-center"><p className="text-lg font-bold font-mono text-[--color-accent]">{c.value}</p><p className="text-[10px] text-[--color-text-muted]">{c.label}</p></div>)}</div><FrequencyTable data={statsData.table}/><BarChartViz data={statsData.table.map(r=>({value:r.value,freq:r.freq}))} mean={statsData.mean} median={statsData.median} q1={statsData.q1} q3={statsData.q3} title="Diagramme en barres"/></>}<StepDisplay steps={stSteps} result={stResult}/></>}

    {tab==='grouped'&&<><div className="rounded-xl bg-[--color-accent-subtle] p-3 text-xs text-[--color-text-secondary]"><strong>Programme 3e Madagascar :</strong> classes d'égale amplitude, histogramme, effectifs/fréquences cumulés et classe modale.</div><InputField label="Bornes des classes" value={bounds} onChange={setBounds} placeholder="0, 5, 10, 15, 20"/><InputField label="Effectifs par classe" value={groupFreqs} onChange={setGroupFreqs} placeholder="17, 11, 12, 10"/><p className="text-[10px] text-[--color-text-muted]">Exemple : bornes 0,5,10,15,20 donnent [0;5[, [5;10[, [10;15[, [15;20[.</p><SolveButton onClick={solveGrouped} label="Compléter et analyser"/>{grouped&&<><div className="overflow-x-auto rounded-xl border border-[--color-border]"><table className="w-full text-xs"><thead className="bg-[--color-inset]"><tr><th className="p-2 text-left">Classe</th><th>Centre</th><th>Effectif</th><th>Fréq.</th><th>Cumul</th></tr></thead><tbody>{grouped.rows.map((r,i)=><tr key={i} className="border-t border-[--color-border]"><td className="p-2 font-mono">[{r.lower};{r.upper}[</td><td className="text-center">{r.center}</td><td className="text-center">{r.freq}</td><td className="text-center">{(r.relative*100).toFixed(1)}%</td><td className="text-center">{r.cumulative}</td></tr>)}</tbody></table></div><div className="grid grid-cols-3 gap-3"><div className="p-3 rounded-xl bg-[--color-inset] text-center"><p className="font-bold text-[--color-accent]">{grouped.n}</p><p className="text-[10px] text-[--color-text-muted]">Effectif total</p></div><div className="p-3 rounded-xl bg-[--color-inset] text-center"><p className="font-bold text-[--color-accent]">{grouped.mean.toFixed(2)}</p><p className="text-[10px] text-[--color-text-muted]">Moyenne approx.</p></div><div className="p-3 rounded-xl bg-[--color-inset] text-center"><p className="font-bold text-[--color-accent]">{grouped.modalClasses.join(', ')}</p><p className="text-[10px] text-[--color-text-muted]">Classe modale</p></div></div><GroupedHistogram rows={grouped.rows}/></>}<StepDisplay steps={groupSteps} result={groupResult}/></>}

    {tab==='proportion'&&<><p className="text-sm text-[--color-text-secondary]">Vérifier ou calculer une situation de proportionnalité.</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-4"><InputField label="x₁" value={px1} onChange={setPx1} placeholder="3"/><InputField label="y₁" value={py1} onChange={setPy1} placeholder="12"/><InputField label="x₂" value={px2} onChange={setPx2} placeholder="5"/><InputField label="y₂ (vide=chercher)" value={py2} onChange={setPy2}/></div><SolveButton onClick={solvePr} label="Calculer"/><StepDisplay steps={prSteps} result={prResult}/></>}

    {tab==='percent'&&<><div className="grid grid-cols-2 sm:grid-cols-4 gap-2">{[{id:'of',l:'% de…'},{id:'increase',l:'Augmentation'},{id:'decrease',l:'Diminution'},{id:'whatPercent',l:'Quel % ?'}].map(t=><TabButton key={t.id} active={pType===t.id} onClick={()=>setPType(t.id)}>{t.l}</TabButton>)}</div><div className="grid grid-cols-2 gap-4"><InputField label={pType==='whatPercent'?'Total':'Valeur'} value={pVal} onChange={setPVal} placeholder="200"/><InputField label={pType==='whatPercent'?'Partie':'%'} value={pPer} onChange={setPPer} placeholder="15"/></div><SolveButton onClick={solvePe} label="Calculer"/><StepDisplay steps={peSteps} result={peResult}/></>}
  </div>;
}
