import { useMemo, useState } from 'react';
import type { Lang } from '../utils/i18n';
import PageHeader from './PageHeader';

interface Lesson {
  id:string; title:string; mgTitle:string; formula:string[];
  summary:{fr:string;mg:string}; method:{fr:string[];mg:string[]}; mistakes:{fr:string[];mg:string[]};
}

const lessons:Lesson[]=[
  {id:'fractions',title:'Fractions & rationnels',mgTitle:'Fraction sy isa rationnel',formula:['a/b + c/d = (ad + bc)/bd','a/b × c/d = ac/bd','a/b ÷ c/d = ad/bc'],summary:{fr:'Simplifier une fraction, calculer avec des dénominateurs différents et utiliser PGCD/PPCM.',mg:'Mampihena fraction, manao kajy amin’ny dénominateur samihafa ary mampiasa PGCD/PPCM.'},method:{fr:['Simplifie les fractions si possible.','Pour + ou −, cherche un dénominateur commun.','Pour ÷, multiplie par l’inverse.'],mg:['Ahena aloha ny fraction raha azo atao.','Raha + na − dia mitadiava dénominateur commun.','Raha ÷ dia ampitomboy amin’ny inverse.']},mistakes:{fr:['Additionner les dénominateurs.','Oublier de simplifier le résultat.'],mg:['Manampy dénominateur mivantana.','Manadino mampihena ny valiny.']}},
  {id:'radicals',title:'Racines carrées',mgTitle:'Racine carrée',formula:['√(a²b) = a√b','√a × √b = √(ab)'],summary:{fr:'Reconnaître les carrés parfaits et sortir les facteurs carrés de la racine.',mg:'Mahafantatra carré parfait ary mamoaka facteur carré ivelan’ny racine.'},method:{fr:['Décompose le nombre en produit.','Repère un carré parfait.','Sors sa racine devant √.'],mg:['Zarazarao ho produit ilay isa.','Tadiavo ny carré parfait.','Avoahy eo alohan’ny √ ny racine-ny.']},mistakes:{fr:['Écrire √(a+b)=√a+√b.','Simplifier un radicande négatif dans ℝ.'],mg:['Manoratra √(a+b)=√a+√b.','Manao racine négatif ao amin’ny ℝ.']}},
  {id:'powers',title:'Puissances',mgTitle:'Puissance',formula:['aᵐ × aⁿ = aᵐ⁺ⁿ','aᵐ ÷ aⁿ = aᵐ⁻ⁿ','(aᵐ)ⁿ = aᵐⁿ'],summary:{fr:'Utiliser les règles des exposants sans développer inutilement.',mg:'Mampiasa ny fitsipiky ny exposant nefa tsy manao multiplication lava.'},method:{fr:['Vérifie que les bases sont identiques.','Choisis la règle adaptée.','Calcule seulement à la fin si nécessaire.'],mg:['Jereo raha mitovy ny base.','Safidio ny règle mifanaraka.','Kajio amin’ny farany raha ilaina.']},mistakes:{fr:['Additionner les exposants lors d’une addition.','Confondre (a+b)² et a²+b².'],mg:['Manampy exposant rehefa addition.','Mampifangaro (a+b)² sy a²+b².']}},
  {id:'absolute',title:'Valeur absolue',mgTitle:'Valeur absolue',formula:['|x| = distance entre x et 0','|x| = a ⇒ x = a ou x = −a (a≥0)'],summary:{fr:'La valeur absolue représente une distance, donc elle est toujours positive ou nulle.',mg:'Ny valeur absolue dia elanelana ka tsy mety ho négatif.'},method:{fr:['Interprète |ax+b| comme une distance.','Pour une équation, traite les deux signes.','Pour une inéquation, représente l’intervalle.'],mg:['Jereo ho distance ny |ax+b|.','Amin’ny équation dia diniho ny signe roa.','Amin’ny inéquation dia asehoy amin’ny intervalle.']},mistakes:{fr:['Donner une seule solution à |x|=a.','Accepter |x| = nombre négatif.'],mg:['Manome solution iray monja amin’ny |x|=a.','Manaiky |x| mitovy amin’ny isa négatif.']}},
  {id:'development',title:'Développement',mgTitle:'Développement',formula:['(a+b)² = a²+2ab+b²','(a−b)² = a²−2ab+b²','(a+b)(a−b)=a²−b²'],summary:{fr:'Développer signifie supprimer les parenthèses avec la distributivité puis réduire.',mg:'Développer dia manala parenthèse amin’ny distributivité ary manambatra termes mitovy.'},method:{fr:['Multiplie chaque terme.','Respecte les signes.','Regroupe les termes semblables.'],mg:['Ampitomboy ny terme tsirairay.','Tandremo ny signe.','Atambaro ireo termes mitovy.']},mistakes:{fr:['Oublier le terme 2ab.','Perdre le signe −.'],mg:['Manadino ny 2ab.','Very ny signe −.']}},
  {id:'factorization',title:'Factorisation',mgTitle:'Factorisation',formula:['ab+ac = a(b+c)','a²−b²=(a−b)(a+b)'],summary:{fr:'Factoriser est l’opération inverse du développement : on transforme une somme en produit.',mg:'Factoriser dia mifanohitra amin’ny développement: somme no ovaina ho produit.'},method:{fr:['Cherche d’abord un facteur commun.','Sinon teste une identité remarquable.','Vérifie en redéveloppant.'],mg:['Mitadiava facteur commun aloha.','Raha tsy misy dia jereo identité remarquable.','Hamarino amin’ny redéveloppement.']},mistakes:{fr:['Sortir un facteur qui ne divise pas tous les termes.','Ne pas vérifier le résultat.'],mg:['Mamoaka facteur tsy mizara ny termes rehetra.','Tsy manamarina ny valiny.']}},
  {id:'equations',title:'Équations & inéquations',mgTitle:'Équation sy inéquation',formula:['ax+b=c ⇒ x=(c−b)/a','Δ=b²−4ac'],summary:{fr:'Résoudre une équation consiste à trouver toutes les valeurs qui rendent l’égalité vraie.',mg:'Ny famahana équation dia fitadiavana ny sanda rehetra mahatonga ny fitoviana ho marina.'},method:{fr:['Regroupe les x d’un côté et les nombres de l’autre.','Effectue la même opération des deux côtés.','Vérifie la solution.'],mg:['Atambaro amin’ny lafiny iray ny x ary amin’ny iray ny isa.','Ataovy mitovy ny opération amin’ny lafiny roa.','Hamarino ny solution.']},mistakes:{fr:['Changer un signe sans justification.','Oublier d’inverser le signe d’une inéquation quand on divise par un nombre négatif.'],mg:['Manova signe tsy misy antony.','Manadino mamadika signe amin’ny inéquation rehefa mizara amin’ny négatif.']}},
  {id:'vectors',title:'Vecteurs & coordonnées',mgTitle:'Vecteur sy coordonnée',formula:['AB⃗=(xB−xA ; yB−yA)','det(u,v)=ux·vy−uy·vx','u·v=ux·vx+uy·vy','droite : ax+by+c=0'],summary:{fr:'Les coordonnées permettent de calculer déplacements, distances et milieux dans un repère.',mg:'Ny coordonnée dia ahafahana manao kajy déplacement, distance ary milieu ao amin’ny repère.'},method:{fr:['Respecte l’ordre arrivée − départ.','Pour un milieu, fais la moyenne des coordonnées.'],mg:['Tandremo ny filaharana arrivée − départ.','Amin’ny milieu dia moyenne-n’ny coordonnée no atao.']},mistakes:{fr:['Faire xA−xB au lieu de xB−xA.','Mélanger abscisse et ordonnée.'],mg:['Manao xA−xB fa tsy xB−xA.','Mampifangaro abscisse sy ordonnée.']}},
  {id:'geometry',title:'Géométrie plane',mgTitle:'Géométrie plane',formula:['c²=a²+b²','sin θ=opposé/hypoténuse','cos θ=adjacent/hypoténuse','tan θ=opposé/adjacent'],summary:{fr:'Pythagore, Thalès et trigonométrie servent à calculer des longueurs et des angles avec des conditions précises.',mg:'Pythagore, Thalès ary trigonométrie dia ampiasaina amin’ny halavana sy zoro rehefa voahaja ny fepetra.'},method:{fr:['Dessine et nomme les données.','Identifie le théorème adapté.','Écris la formule avant de remplacer les valeurs.'],mg:['Manaova sary ary asio anarana ny données.','Fantaro ny théorème mety.','Soraty aloha ny formule vao soloina sanda.']},mistakes:{fr:['Utiliser Pythagore sans triangle rectangle.','Utiliser Thalès sans parallèles.'],mg:['Mampiasa Pythagore nefa tsy triangle rectangle.','Mampiasa Thalès nefa tsy parallèle.']}},
  {id:'space',title:'Géométrie dans l’espace',mgTitle:'Géométrie dans l’espace',formula:['Vcône=πr²h/3','Vpyramide=Bh/3','aires × k²','volumes × k³'],summary:{fr:'Les volumes dépendent de dimensions positives et d’unités cohérentes.',mg:'Ny volume dia mila dimension positif sy unité mitovy.'},method:{fr:['Identifie le solide.','Choisis la formule.','Vérifie les unités avant le calcul.'],mg:['Fantaro ilay solide.','Safidio ny formule.','Jereo ny unité alohan’ny kajy.']},mistakes:{fr:['Oublier le /3 du cône ou de la pyramide.','Mélanger cm² et cm³.'],mg:['Manadino /3 amin’ny cône na pyramide.','Mampifangaro cm² sy cm³.']}},
  {id:'stats',title:'Statistiques & proportionnalité',mgTitle:'Statistique sy proportionnalité',formula:['moyenne=Σ(xᵢnᵢ)/Σnᵢ','fréquence=nᵢ/N','classe modale=max(effectif)','pourcentage=partie/total×100'],summary:{fr:'Organiser les données, calculer moyenne/médiane/quartiles et reconnaître une situation de proportionnalité.',mg:'Mandamina données, manao moyenne/médiane/quartile ary mahafantatra proportionnalité.'},method:{fr:['Trie les valeurs pour la médiane et les quartiles.','Utilise les effectifs dans la moyenne.','Pour un pourcentage, pense “sur 100”.'],mg:['Alaharo ny sanda ho an’ny médiane sy quartile.','Ampiasao ny effectif amin’ny moyenne.','Amin’ny pourcentage dia eritrereto “amin’ny 100”.']},mistakes:{fr:['Oublier les effectifs.','Confondre valeur et pourcentage.'],mg:['Manadino effectif.','Mampifangaro valeur sy pourcentage.']}},
  {id:'functions',title:'Applications affines & linéaires',mgTitle:'Application affine sy linéaire',formula:['f(x)=ax+b','coefficient directeur = a','f(x)=0 ⇒ x=−b/a'],summary:{fr:'Calculer images et antécédents, lire le sens de variation et représenter une droite.',mg:'Mikajy image sy antécédent, mamantatra variation ary maneho droite.'},method:{fr:['Repère a et b dans f(x)=ax+b.','Pour une image, remplace x.','Pour un antécédent, résous ax+b=y.','Pour le graphique, place deux points puis trace la droite.'],mg:['Fantaro ny a sy b ao amin’ny f(x)=ax+b.','Ho an’ny image dia soloina x.','Ho an’ny antécédent dia vahao ax+b=y.','Ho an’ny graphique dia apetraho point roa ary soraty ny droite.']},mistakes:{fr:['Confondre image et antécédent.','Oublier que le signe de a donne le sens de variation.'],mg:['Mampifangaro image sy antécédent.','Manadino fa ny signe an’i a no mamaritra variation.']}},
  {id:'circle',title:'Angles inscrits dans un cercle',mgTitle:'Zoro inscrit ao anaty cercle',formula:['angle inscrit = 1/2 × angle au centre','même arc ⇒ mêmes angles inscrits','diamètre intercepté ⇒ 90°'],summary:{fr:'Reconnaître angle au centre, angle inscrit et arc intercepté puis appliquer les propriétés.',mg:'Mahafantatra angle au centre, angle inscrit ary arc intercepté ary mampiasa ny propriétés.'},method:{fr:['Identifie l’arc intercepté.','Vérifie si les deux angles sont associés au même arc.','Applique moitié/double ou l’égalité des angles inscrits.'],mg:['Fantaro ny arc intercepté.','Jereo raha arc iray ihany no tapahin’ireo zoro.','Ampiasao moitié/double na égalité des angles inscrits.']},mistakes:{fr:['Doubler l’angle inscrit dans le mauvais sens.','Utiliser la propriété sur deux arcs différents.'],mg:['Manao double amin’ny lafiny diso.','Mampiasa propriété amin’ny arc samihafa.']}},
];

export default function Lessons({lang,onOpenChapter}:{lang:Lang;onOpenChapter:(id:string)=>void}){
  const [search,setSearch]=useState('');
  const [open,setOpen]=useState<string|null>(null);
  const filtered=useMemo(()=>lessons.filter(l=>[l.title,l.mgTitle,l.summary.fr,l.summary.mg].join(' ').toLowerCase().includes(search.toLowerCase())),[search]);
  const mg=lang==='mg';
  return <div className="page-medium animate-fade-up">
    <PageHeader title={mg?'Famintinana lesona':'Réviser les cours'} description={mg?'Formule ilaina, fomba fanao ary fahadisoana tokony hialana.':'Les formules essentielles, les méthodes et les erreurs à éviter pour le BEPC.'}/>
    <label className="search-box"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><circle cx="11" cy="11" r="7"/><path d="m20 20-3.5-3.5"/></svg><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={mg?'Mitady lesona…':'Rechercher une notion…'}/></label>
    <div className="lesson-list">{filtered.map(l=><article key={l.id} className={'lesson-card '+(open===l.id?'is-open':'')}>
      <button type="button" onClick={()=>setOpen(open===l.id?null:l.id)} className="lesson-card-head"><div className="min-w-0"><h2>{mg?l.mgTitle:l.title}</h2><p>{l.summary[lang]}</p></div><span className="lesson-toggle">{open===l.id?'−':'+'}</span></button>
      {open===l.id&&<div className="lesson-details">
        <section><h3>Formules</h3><div className="formula-list">{l.formula.map(f=><div key={f} className="formula-card">{f}</div>)}</div></section>
        <section><h3>{mg?'Fomba fanao':'Méthode'}</h3><ol className="method-list">{l.method[lang].map((m,i)=><li key={m}><span>{i+1}</span><p>{m}</p></li>)}</ol></section>
        <section><h3>{mg?'Fahadisoana ialana':'Erreurs à éviter'}</h3><ul className="mistake-list">{l.mistakes[lang].map(m=><li key={m}>{m}</li>)}</ul><button type="button" onClick={()=>onOpenChapter(l.id)} className="secondary-button w-full">{mg?'Hanao kajy':'Ouvrir les exercices'}</button></section>
      </div>}
    </article>)}</div>
  </div>;
}
